### ISSUE TITLE
Running command in Host fails when `/etc/iproute2/group` not present

### ISSUE THREAD

**Issue by Infinoid** [cunicu/gont#161]
[Here](https://gist.github.com/Infinoid/bf7e729025e38cf6979403e0fbcb6f9d) is a simple test program which creates a host and runs the command "ip addr" in it.

This succeeds when the file `/etc/iproute2/group` exists:

```console
% sudo touch /etc/iproute2/group     
% sudo go run .
ip addr said:
----
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 brd 127.255.255.255 scope global lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever

----
success
% 
```

And it fails when that file is missing.

```console
% sudo rm -v /etc/iproute2/group
removed '/etc/iproute2/group'
% sudo go run .                 
cmd.CombinedOutput() failed: exit status 2
failure
% 
```

If I ignore the error and print the combined output, I see a little more information:

```
panic: failed setup network bind mounts: failed to mount: no such file or directory

goroutine 1 [running]:
cunicu.li/gont/v2/pkg.init.0()
	/root/go/pkg/mod/cunicu.li/gont/v2@v2.5.0/pkg/exec.go:49 +0x185

```

And if I run it in strace, I see this sequence of syscalls:

```strace
newfstatat(AT_FDCWD, "/var/run/gont/testnet/files/etc/iproute2/.mount",  0xc0001e7078, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/var/run/gont/testnet/files/etc/iproute2/group", {st_mode=S_IFREG|0644, st_size=34, ...}, AT_SYMLINK_NOFOLLOW) = 0
mount("/var/run/gont/testnet/files/etc/hosts", "/etc/hosts", 0xc000130fab, MS_BIND, NULL) = 0
mount("/var/run/gont/testnet/files/etc/iproute2/group", "/etc/iproute2/group", 0xc000130fac, MS_BIND, NULL) = -1 ENOENT (No such file or directory)
```

Are you always running gont on hosts where that file is present?  Because it's not present here on this Debian box, and that seems to break command execution.  Even the `/etc/iproute2` folder didn't exist, I created it while tracking this down.

**Comment by Infinoid** [comment]
Looking at it further, this seems to be specific to Debian trixie (testing), for now.  The file doesn't exist in Debian trixie, but it does exist in Debian bookworm and bullseye, and Ubuntu noble, focal and bionic.

Debian trixie's version of iproute2 is 6.8.0, which is newer than the others.  [Their changelog](https://metadata.ftp-master.debian.org/changelogs//main/i/iproute2/iproute2_6.8.0-1_changelog) seems to suggest that they're just following the upstream's lead.

And indeed, [this commit](https://git.kernel.org/pub/scm/network/iproute2/iproute2.git/commit/?h=v6.5.0&id=0a0a8f12fa1b03dd0ccbebf5f85209d1c8a0f580) is when they switched to installing stuff in /usr rather than /etc, and reading from both, such that /etc overrides /usr.

So, you probably shouldn't rely on it existing in `/etc/iproute2/` in the future.  Though it might be a year or so before everyone starts tripping over this.

**Comment by Infinoid** [comment]
That commit mentions `/usr/lib/iproute2`, but the Debian package installs it to `/usr/share/iproute2/group`.  Because Debian has strong opinions about these paths.

**Comment by stv0g** [comment]
I have the same issue with my NixOS setup, in which `/etc/iproute2` does not exist by default.

I implemented a fix in #162 by checking if all target base directories exist before attempting to bind mount files.

**Comment by Infinoid** [comment]
It looks to me like it's bind-mounting the actual file, not the folder.

```
mount("/var/run/gont/testnet/files/etc/iproute2/group", "/etc/iproute2/group", 0xc000130fac, MS_BIND, NULL) = -1 ENOENT (No such file or directory)
```

**Comment by stv0g** [comment]
> It looks to me like it's bind-mounting the actual file, not the folder.

Yes this is intended, as if the target folder already exists, we do not want to shadow any pre-existing files by the bind mount. So we rather bind-mount each file independently.

**Comment by Infinoid** [comment]
Thanks for the fix.

I did a `go get cunicu.li/gont/v2@main` and verified that I was able to run gont tests without a group file present.  It ran and the tests passed.  But it looks like it *created* a new `/etc/iproute2` folder and an empty `/etc/iproute2/group` file.

Was that what you intended?  It seems a little weird to me.  But if it doesn't break anything, I guess we can ignore it.

**Comment by Infinoid** [comment]
> But if it doesn't break anything,

It does break things; I will submit a new issue for it.
